version: '2'

services:
  web:
    restart: always
    build: .
    expose:
      - "3011"
    # volumes:
      # - /usr/src/app/public:/usr/src/app/public:ro
    environment:
      - VIRTUAL_HOST=interlinerecords.com,www.interlinerecords.com
      - LETSENCRYPT_HOST=interlinerecords.com,www.interlinerecords.com
      - LETSENCRYPT_EMAIL=info@interlinerecords.com
      - LETSENCRYPT_TEST=false
      - NODE_ENV=production
    command: /usr/src/app/startup.sh
    networks:
      - proxy
      - default

networks:
  proxy:
    external:
      name: proxy
