version: '2'

services:
  web:
    restart: always
    build: .
    expose:
      - "3011"
    volumes:
      - /usr/src/app/public:/usr/src/app/public:rw
    env_file: .env
    environment:
      - VIRTUAL_HOST=interline.in,www.interline.in
      - LETSENCRYPT_HOST=interline.in,www.interline.in
      - LETSENCRYPT_EMAIL=info@interline.in
      - LETSENCRYPT_TEST=true
    command: /usr/src/app/startup.sh
    networks:
      - proxy
      - default

networks:
  proxy:
    external:
      name: proxy
